---
abstract: 'Locale::TextDomain::OO - Perl OO Interface to Uniforum Message Translation'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  DBD::PO::Locale::PO: 0
  Test::Deep: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-TextDomain-OO
provides:
  Locale::TextDomain::OO:
    file: lib/Locale/TextDomain/OO.pm
    version: 0.07
  Locale::TextDomain::OO::FunctionalInterface:
    file: lib/Locale/TextDomain/OO/FunctionalInterface.pm
    version: v0.3.0
  Locale::TextDomain::OO::Maketext:
    file: lib/Locale/TextDomain/OO/Maketext.pm
    version: v0.3.0
  Locale::TextDomain::OO::MessagesStruct:
    file: lib/Locale/TextDomain/OO/MessagesStruct.pm
    version: v0.3.0
  Locale::TextDomain::OO::TiedInterface:
    file: lib/Locale/TextDomain/OO/TiedInterface.pm
    version: v0.3.0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  Cwd: 0
  DBD::PO: 2.09
  DBI: 0
  Encode: 0
  English: 0
  I18N::LangTags: 0
  I18N::LangTags::Detect: 0
  Locale::Messages: 1.2
  Perl6::Export::Attrs: 0
  Safe: 0
  Tie::Sub: 0.09
  parent: 0
  perl: 5.006
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
